library gboard;
import 'package:flutter/widgets.dart';
import 'package:flutter/rendering.dart';
import 'package:ch48/tinygame.dart';
import 'dart:math' as math;
import '../glogic/glogic.dart';
part 'programscene.dart';
part 'rangeselect.dart';
part 'setting.dart';
part 'tipselect.dart';
part 'tipsetting.dart';
